---
- name: Trabalhando com template jinja2
  hosts: all
  vars: 
    http_port: 80

  tasks:
  - name: Valida que o Apache esteja na última versão
    yum: name=httpd state=latest 

  - name: Substituia o arquivo de configuração httd.conf 
    template: src=templates/httpd.conf.j2 dest=/etc/httpd/httpd.conf 
    notify:
    - restart apache

  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes

  handlers:
    - name: restart apache
      service: name=httpd state=restarted